### ISSUE TITLE
Import orientation issues 

### ISSUE THREAD

**Issue by alusion** [void4/FireVR#14]
I'm trying to precisely align my 3D model in JanusVR then import into blender and I'm having issues where the model will import with models spun the wrong direction or distanced apart. This tool is amazing for combining in Janus then optimizing in blender but this issue adds a lot more work to do after importing.

**Comment by Spyduck** [comment]
Seems to be fixed now.
https://github.com/void4/FireVR/commit/dbc92741e0db9e16f47ae6ab9e2c31388d9be4a2
